### ISSUE TITLE
Don't steal names

### ISSUE THREAD

**Issue by pseeger** [Martin-Eckleben/WhoCanBeDrunk-traveling-salesman-in-Prolog#1]
;-) Irgendwoher kommen diese Namen in den Prädikaten, ich hab da nur garkeine klare Idee gerade :=)

**Comment by Martin-Eckleben** [comment]
Hey @pseeger grad das hier wieder gesehen und musste grinsen.
Ich bin jetzt einer der ersten neuen Maintainer von Flameshot einer Screenshot Software in den offiziellen Ubuntu Repos.
Du hast gute Arbeit geleistet mich technisch zu erziehen :))
